# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fct_comp_8.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fct_comp_8(object):
    def setupUi(self, fct_comp_8):
        fct_comp_8.setObjectName("fct_comp_8")
        fct_comp_8.setEnabled(True)
        fct_comp_8.resize(594, 469)
        self.verticalLayout = QtWidgets.QVBoxLayout(fct_comp_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(fct_comp_8)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table_fct_8 = QtWidgets.QTableWidget(fct_comp_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_fct_8.sizePolicy().hasHeightForWidth())
        self.table_fct_8.setSizePolicy(sizePolicy)
        self.table_fct_8.setObjectName("table_fct_8")
        self.table_fct_8.setColumnCount(3)
        self.table_fct_8.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_8.setHorizontalHeaderItem(2, item)
        self.table_fct_8.horizontalHeader().setDefaultSectionSize(200)
        self.table_fct_8.horizontalHeader().setMinimumSectionSize(50)
        self.table_fct_8.horizontalHeader().setStretchLastSection(False)
        self.table_fct_8.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.table_fct_8)
        self.label_mid = QtWidgets.QLabel(fct_comp_8)
        self.label_mid.setText("")
        self.label_mid.setObjectName("label_mid")
        self.verticalLayout.addWidget(self.label_mid)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(fct_comp_8)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(fct_comp_8)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(fct_comp_8)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.box_sp_s = QtWidgets.QComboBox(fct_comp_8)
        self.box_sp_s.setObjectName("box_sp_s")
        self.horizontalLayout_5.addWidget(self.box_sp_s)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(fct_comp_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.box_dr_s = QtWidgets.QComboBox(fct_comp_8)
        self.box_dr_s.setObjectName("box_dr_s")
        self.horizontalLayout_6.addWidget(self.box_dr_s)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.push_delete = QtWidgets.QPushButton(fct_comp_8)
        self.push_delete.setObjectName("push_delete")
        self.verticalLayout_2.addWidget(self.push_delete)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(fct_comp_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.box_sp_a = QtWidgets.QComboBox(fct_comp_8)
        self.box_sp_a.setObjectName("box_sp_a")
        self.horizontalLayout_2.addWidget(self.box_sp_a)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(fct_comp_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(fct_comp_8)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.push_add = QtWidgets.QPushButton(fct_comp_8)
        self.push_add.setObjectName("push_add")
        self.verticalLayout_3.addWidget(self.push_add)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.push_fer = QtWidgets.QPushButton(fct_comp_8)
        self.push_fer.setObjectName("push_fer")
        self.horizontalLayout_8.addWidget(self.push_fer)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_8)

        self.retranslateUi(fct_comp_8)
        self.push_add.clicked.connect(fct_comp_8.add_representation)
        self.push_fer.clicked.connect(fct_comp_8.close)
        self.box_sp_s.currentTextChanged['QString'].connect(fct_comp_8.refresh_s_dateRep)
        self.push_delete.clicked.connect(fct_comp_8.delete_representation)
        QtCore.QMetaObject.connectSlotsByName(fct_comp_8)

    def retranslateUi(self, fct_comp_8):
        _translate = QtCore.QCoreApplication.translate
        fct_comp_8.setWindowTitle(_translate("fct_comp_8", "Gestion de représentations"))
        self.label.setText(_translate("fct_comp_8", "Gérer les représentations"))
        item = self.table_fct_8.horizontalHeaderItem(0)
        item.setText(_translate("fct_comp_8", "noSpec"))
        item = self.table_fct_8.horizontalHeaderItem(1)
        item.setText(_translate("fct_comp_8", "dateRep"))
        item = self.table_fct_8.horizontalHeaderItem(2)
        item.setText(_translate("fct_comp_8", "nbPlaceDispo"))
        self.label_5.setText(_translate("fct_comp_8", "Suppression d\'une représentation existante"))
        self.label_2.setText(_translate("fct_comp_8", "Ajout d\'une nouvelle représentation"))
        self.label_6.setText(_translate("fct_comp_8", "Choisir le numéro Spectacle"))
        self.label_7.setText(_translate("fct_comp_8", "Choisi la date Représentation"))
        self.push_delete.setText(_translate("fct_comp_8", "Supprimer"))
        self.label_4.setText(_translate("fct_comp_8", "Choisi le numéro Spectacle"))
        self.label_3.setText(_translate("fct_comp_8", "Saisir une nouvelle date"))
        self.push_add.setText(_translate("fct_comp_8", "Ajouter"))
        self.push_fer.setText(_translate("fct_comp_8", "Fermer"))

