# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fct_comp_9.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fct_comp_9(object):
    def setupUi(self, fct_comp_9):
        fct_comp_9.setObjectName("fct_comp_9")
        fct_comp_9.resize(500, 528)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(fct_comp_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(fct_comp_9)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(fct_comp_9)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(fct_comp_9)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(fct_comp_9)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.table_fct_comp_9 = QtWidgets.QTableWidget(fct_comp_9)
        self.table_fct_comp_9.setObjectName("table_fct_comp_9")
        self.table_fct_comp_9.setColumnCount(6)
        self.table_fct_comp_9.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_9.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_9.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_9.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_9.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_9.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_fct_comp_9.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.table_fct_comp_9)
        self.label_bas = QtWidgets.QLabel(fct_comp_9)
        self.label_bas.setText("")
        self.label_bas.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bas.setObjectName("label_bas")
        self.verticalLayout_3.addWidget(self.label_bas)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(fct_comp_9)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(fct_comp_9)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(fct_comp_9)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(fct_comp_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.box_ns_a = QtWidgets.QComboBox(fct_comp_9)
        self.box_ns_a.setObjectName("box_ns_a")
        self.verticalLayout_7.addWidget(self.box_ns_a)
        self.box_dr_a = QtWidgets.QComboBox(fct_comp_9)
        self.box_dr_a.setObjectName("box_dr_a")
        self.verticalLayout_7.addWidget(self.box_dr_a)
        self.box_nr_a = QtWidgets.QComboBox(fct_comp_9)
        self.box_nr_a.setObjectName("box_nr_a")
        self.verticalLayout_7.addWidget(self.box_nr_a)
        self.box_np_a = QtWidgets.QComboBox(fct_comp_9)
        self.box_np_a.setObjectName("box_np_a")
        self.verticalLayout_7.addWidget(self.box_np_a)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.push_ajout = QtWidgets.QPushButton(fct_comp_9)
        self.push_ajout.setObjectName("push_ajout")
        self.verticalLayout_6.addWidget(self.push_ajout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.box_ns_s = QtWidgets.QComboBox(fct_comp_9)
        self.box_ns_s.setObjectName("box_ns_s")
        self.verticalLayout_2.addWidget(self.box_ns_s)
        self.box_dr_s = QtWidgets.QComboBox(fct_comp_9)
        self.box_dr_s.setObjectName("box_dr_s")
        self.verticalLayout_2.addWidget(self.box_dr_s)
        self.box_nr_s = QtWidgets.QComboBox(fct_comp_9)
        self.box_nr_s.setObjectName("box_nr_s")
        self.verticalLayout_2.addWidget(self.box_nr_s)
        self.box_np_s = QtWidgets.QComboBox(fct_comp_9)
        self.box_np_s.setObjectName("box_np_s")
        self.verticalLayout_2.addWidget(self.box_np_s)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.push_delete = QtWidgets.QPushButton(fct_comp_9)
        self.push_delete.setObjectName("push_delete")
        self.verticalLayout_4.addWidget(self.push_delete)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.push_fer = QtWidgets.QPushButton(fct_comp_9)
        self.push_fer.setObjectName("push_fer")
        self.horizontalLayout_2.addWidget(self.push_fer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(fct_comp_9)
        self.pushButton.clicked.connect(fct_comp_9.refreshResult)
        self.box_ns_a.currentTextChanged['QString'].connect(fct_comp_9.refresh_dateRep)
        self.box_dr_a.currentTextChanged['QString'].connect(fct_comp_9.refresh_noRang)
        self.box_nr_a.currentTextChanged['QString'].connect(fct_comp_9.refresh_noPlace)
        self.push_ajout.clicked.connect(fct_comp_9.add_reservation)
        self.push_fer.clicked.connect(fct_comp_9.close)
        self.box_ns_s.currentTextChanged['QString'].connect(fct_comp_9.refresh_s_dateRep)
        self.box_dr_s.currentTextChanged['QString'].connect(fct_comp_9.refresh_s_noRang)
        self.box_nr_s.currentTextChanged['QString'].connect(fct_comp_9.refresh_s_noPlace)
        self.push_delete.clicked.connect(fct_comp_9.delete_reservation)
        QtCore.QMetaObject.connectSlotsByName(fct_comp_9)

    def retranslateUi(self, fct_comp_9):
        _translate = QtCore.QCoreApplication.translate
        fct_comp_9.setWindowTitle(_translate("fct_comp_9", "Gestion de réservations"))
        self.label.setText(_translate("fct_comp_9", "Donner un login pour consulter les réservations correspondentes"))
        self.label_2.setText(_translate("fct_comp_9", "Login:"))
        self.pushButton.setText(_translate("fct_comp_9", "OK"))
        item = self.table_fct_comp_9.horizontalHeaderItem(0)
        item.setText(_translate("fct_comp_9", "Nom"))
        item = self.table_fct_comp_9.horizontalHeaderItem(1)
        item.setText(_translate("fct_comp_9", "Prenom"))
        item = self.table_fct_comp_9.horizontalHeaderItem(2)
        item.setText(_translate("fct_comp_9", "noSpec"))
        item = self.table_fct_comp_9.horizontalHeaderItem(3)
        item.setText(_translate("fct_comp_9", "dateRep"))
        item = self.table_fct_comp_9.horizontalHeaderItem(4)
        item.setText(_translate("fct_comp_9", "noPlace"))
        item = self.table_fct_comp_9.horizontalHeaderItem(5)
        item.setText(_translate("fct_comp_9", "noRang"))
        self.label_3.setText(_translate("fct_comp_9", "Choisir noSpec"))
        self.label_4.setText(_translate("fct_comp_9", "Choisir dateRep"))
        self.label_5.setText(_translate("fct_comp_9", "Choisir noRang"))
        self.label_6.setText(_translate("fct_comp_9", "Choisir noPlace"))
        self.push_ajout.setText(_translate("fct_comp_9", "Ajouter"))
        self.push_delete.setText(_translate("fct_comp_9", "Suprrimer"))
        self.push_fer.setText(_translate("fct_comp_9", "Fermer"))

